import { createHash, randomBytes } from "node:crypto";
import { getToken } from "next-auth/jwt";
import { getPool } from "@/lib/db";
import { sessionCookieName, secureCookies } from "@/server/session-cookie";

// Desktop login handoff, step 1: a signed-in BROWSER session asks for a
// one-time code the Electron app can later exchange for its own session
// cookie. Body: { challenge } — base64url(sha256(verifier)) generated by the
// app; the verifier never leaves the app, so an intercepted code is useless.
// Raw JWT claims (getToken, not auth()) so the `uid` claim the Socket.IO
// handshake depends on is preserved byte-for-byte in the re-encoded session.
export async function POST(req: Request) {
  const token = await getToken({
    req,
    secret: process.env.AUTH_SECRET,
    secureCookie: secureCookies(),
    cookieName: sessionCookieName(),
    salt: sessionCookieName(),
  });
  if (!token?.uid) return new Response("Unauthorized", { status: 401 });

  let body: { challenge?: string };
  try {
    body = await req.json();
  } catch {
    return new Response("Bad body", { status: 400 });
  }
  // A base64url-encoded sha256 is exactly 43 chars unpadded.
  const challenge = body.challenge;
  if (!challenge || !/^[A-Za-z0-9_-]{43}$/.test(challenge)) {
    return new Response("Bad challenge", { status: 400 });
  }

  const code = randomBytes(32).toString("base64url");
  const codeHash = createHash("sha256").update(code).digest("hex");
  // Session-lifetime claims are re-stamped by `encode` at exchange time.
  const claims = { ...(token as Record<string, unknown>) };
  delete claims.iat;
  delete claims.exp;
  delete claims.jti;

  const pool = getPool();
  await pool.query(
    "INSERT INTO desktop_auth_code (code_hash, token, challenge) VALUES ($1,$2,$3)",
    [codeHash, JSON.stringify(claims), challenge],
  );
  // Opportunistic sweep of long-dead codes (TTL is enforced at exchange).
  void pool
    .query(
      "DELETE FROM desktop_auth_code WHERE created_at < now() - interval '10 minutes'",
    )
    .catch(() => {});

  return Response.json({ code });
}
